name: 'Build launcher'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.config'
      - '*.props'
      - '*.targets'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.config'
      - '*.props'
      - '*.targets'

defaults:
  run:
    shell: pwsh

jobs:
  build-launcher:
    name: 'Build launcher'

    strategy:
      matrix:
        system:
          - windows-2022
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Solution: AnomalyCustomLauncher.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore packages
        run: |
          dotnet restore $env:Solution

      - name: Build solution
        run: |
          dotnet build $env:Solution `
            --configuration ${{ matrix.config }} `
            --no-restore

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: launcher-bin-${{ matrix.system }}-${{ matrix.config }}-${{ github.sha }}
          path: bin/${{ matrix.config }}/net8.0-windows/
